sudo: false
language: ruby
cache:
  bundler: true

rvm:
  - 2.3.1

script:
  - bundle exec jekyll build

before_deploy:
  - chmod +x publish.sh

deploy:
  provider: script
  script: ./publish.sh
  skip_cleanup: true
