# Site settings
title: The Little Calculist
email: david.herman@gmail.com
author: "David Herman"
description: "Dave Herman's personal blog."
baseurl: ""
url: "http://calculist.org"
timezone: America/Los_Angeles
twitter_username: littlecalculist
github_username:  dherman
#google_analytics: UA-27510188-1
permalink: /blog/:year/:month/:day/:slug/

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 3
excerpt_separator: <!--more-->

exclude:
  - .travis.yml
  - publish.sh
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
